[projects.mypy_primer]
location = "https://github.com/hauntsaninja/mypy_primer"
deps = ["types-setuptools"]

[projects.black]
location = "https://github.com/psf/black"
deps = ["aiohttp", "click", "pathspec", "tomli", "platformdirs", "packaging"]
paths = ["src"]

[projects.pyp]
location = "https://github.com/hauntsaninja/pyp"
deps = ["pytest"]

[projects.git-revise]
location = "https://github.com/mystor/git-revise"
deps = ["pytest"]
paths = ["gitrevise"]

[projects.zipp]
location = "https://github.com/jaraco/zipp"
paths = ["zipp"]

[projects.arrow]
location = "https://github.com/arrow-py/arrow"
paths = ["arrow"]

[projects.isort]
location = "https://github.com/PyCQA/isort"
paths = ["isort"]

[projects.itsdangerous]
location = "https://github.com/pallets/itsdangerous"
paths = ["itsdangerous"]

[projects.rich]
location = "https://github.com/Textualize/rich"
paths = ["rich"]

[projects.packaging]
location = "https://github.com/pypa/packaging"
paths = ["packaging"]

[projects.pybind11]
location = "https://github.com/pybind/pybind11"
paths = ["pybind11"]

[projects.pyinstrument]
location = "https://github.com/joerick/pyinstrument"
paths = ["pyinstrument"]

[projects.typeshed_stats]
location = "https://github.com/astral-sh/typeshed-stats"
paths = ["typeshed_stats"]

[projects.scrapy]
location = "https://github.com/scrapy/scrapy"
deps = ["attrs", "types-pyOpenSSL", "types-setuptools"]

[projects.werkzeug]
location = "https://github.com/pallets/werkzeug"
deps = ["types-setuptools", "pytest", "markupsafe"]

[projects.bidict]
location = "https://github.com/jab/bidict"
paths = ["bidict"]

[projects.async-utils]
location = "https://github.com/astral-sh/async-utils"
paths = ["async_utils"]
