[projects.mypy_primer]
location = "https://github.com/hauntsaninja/mypy_primer"
deps = ["types-setuptools"]

[projects.black]
location = "https://github.com/psf/black"
deps = ["aiohttp", "click", "pathspec", "tomli", "platformdirs", "packaging"]
paths = ["src"]

[projects.pyp]
location = "https://github.com/hauntsaninja/pyp"
deps = ["pytest"]

[projects.git-revise]
location = "https://github.com/mystor/git-revise"
deps = ["pytest"]
paths = ["gitrevise"]

[projects.zipp]
location = "https://github.com/jaraco/zipp"
paths = ["zipp"]

[projects.arrow]
location = "https://github.com/arrow-py/arrow"
deps=["python-dateutil"]
paths = ["arrow"]

[projects.isort]
location = "https://github.com/PyCQA/isort"
paths = ["isort"]
deps = ["types-setuptools"]

[projects.itsdangerous]
location = "https://github.com/pallets/itsdangerous"
deps = ["pytest"]

[projects.rich]
location = "https://github.com/Textualize/rich"
deps = ["attrs"]

[projects.packaging]
location = "https://github.com/pypa/packaging"
paths = ["src"]

[projects.pybind11]
location = "https://github.com/pybind/pybind11"
deps = ["nox", "rich"]

[projects.pyinstrument]
location = "https://github.com/joerick/pyinstrument"

[projects.typeshed_stats]
location = "https://github.com/AlexWaygood/typeshed-stats"
deps=["attrs", "cattrs", "pytest", "aiohttp", "pathspec", "jinja2", "tomli"]

[projects.scrapy]
location = "https://github.com/scrapy/scrapy"
deps = ["attrs", "types-pyOpenSSL", "types-setuptools"]

[projects.werkzeug]
location = "https://github.com/pallets/werkzeug"
deps = ["types-setuptools", "pytest", "markupsafe"]

[projects.bidict]
location = "https://github.com/jab/bidict"

[projects.async-utils]
location = "https://github.com/mikeshardmind/async-utils"
