[project]
name = "ecosystem-analyzer"
version = "0.1.0"
description = "A tool for analyzing Python projects with Red Knot"
dependencies = [
    "gitpython",
    "mypy-primer",
]
requires-python = ">=3.13"

[project.scripts]
ecosystem-analyzer = "ecosystem_analyzer.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
]

[tool.uv.sources]
mypy-primer = { git = "https://github.com/astral-sh/mypy_primer", branch = "add-red-knot-support-v4" }
